authors:
  HOOTSMAN:
    name: Лев Николаевич
    description: HOOTSMAN, Creator
    avatar: https://i.imgur.com/euzEpLG.png
  asm:
   name: Assmodeus
   description: AQUILON, Former member, Victim
   avatar: https://i.imgur.com/IQZYURM.png  
  Delian: 
   name: Delian
   description: AQUILON, Former member
   avatar: https://i.imgur.com/kkTdeid.png  
  SE2k: 
   name: Sir Eblo 2000
   description: AQUILON, Guildmaster 
   avatar: https://i.imgur.com/iQmiwMw.png    
  kisso: 
   name: kiss oчкa
   description: AQUILON, Former member
   avatar: https://i.imgur.com/fNdUhEQ.png  
  sensei: 
   name: SenseiYabai
   description: AQUILON, Former member
   avatar: https://i.imgur.com/pBoIcCL.png
  moon: 
   name: MOON
   description: AQUILON, Manager
   avatar: https://i.imgur.com/rXP2Qle.png
  fatal: 
   name: Fatal1ty
   description: The Hospital, Former member, Whale
   avatar: https://i.imgur.com/jn3oSaT.png
