name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: |
            requirements.txt
      - name: Install dependency
        run: |
         echo "PYTHONPATH=:/home/runner/work/afk.GG/afk.GG/scripts/" >> $GITHUB_ENV
         python -m pip install -r requirements.txt
         echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Make destination directory for compiled CSS
        run: mkdir -vp docs/theme/css
      - name: install node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          ls
          npm i --save-dev @types/jquery
          npm run build
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: docs/src/scss/main.scss
          destination: docs/theme/css/main.css
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Deploy to gh
        run: mkdocs gh-deploy --force
