name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Make destination directory for compiled CSS
        run: mkdir -vp docs/theme/css
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: docs/src/scss/main.scss
          destination: docs/theme/css/main.css
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # - run: |
      #     git remote add gh-token "https://${{ secrets.GH_TOKEN }}@github.com/Hootsdev/afk.GG.git"
      #     git fetch gh-token && git fetch gh-token gh-pages:gh-pages
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-redirects
      - run: pip install mkdocs-table-reader-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-committers-plugin
      - run: pip install openpyxl
      - run: pip install requests     
      - run: pip install pyarrow
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
